"""empty message

Revision ID: 0431378fa5c1
Revises: 2504bf16fab2
Create Date: 2022-06-27 08:01:43.265500

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0431378fa5c1'
down_revision = '2504bf16fab2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='planets')
    op.drop_index('name_2', table_name='planets')
    op.drop_table('planets')
    op.drop_index('name', table_name='people')
    op.drop_index('name_2', table_name='people')
    op.drop_table('people')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('gender', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('birth_year', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('hair_color', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('eye_color', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('height', mysql.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('name_2', 'people', ['name'], unique=False)
    op.create_index('name', 'people', ['name'], unique=False)
    op.create_table('planets',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('terrain', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('population', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('climate', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('diameter', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('gravity', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('rotation_period', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('orbital_period', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('surface_water', mysql.VARCHAR(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('name_2', 'planets', ['name'], unique=False)
    op.create_index('name', 'planets', ['name'], unique=False)
    # ### end Alembic commands ###
