"""empty message

Revision ID: aaa292210c15
Revises: 2a3c6ab86b1a
Create Date: 2022-06-28 07:51:22.946463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaa292210c15'
down_revision = '2a3c6ab86b1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites_people', sa.Column('people_name', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favorites_people', 'people_name')
    # ### end Alembic commands ###
